version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  watcher:
    build: .
    ports:
      - "3000:3000"
    environment:
      WATCH_PATH: /app/dev
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - /home/leonardomalt/Documents/dev:/app/dev
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
